const permissions = [
  // Core admin permissions
  "dashboard.view",
  "users.view",
  "users.create",
  "users.edit",
  "users.delete",
  "students.view",
  "students.create",
  "students.edit",
  "students.delete",
  "settings.view",
  "settings.edit",
  "analytics.view",
  "reports.view",
  "reports.export",
  // Content management permissions
  "programs.view",
  "programs.create",
  "programs.edit",
  "programs.delete",
  "workshops.view",
  "workshops.create",
  "workshops.edit",
  "workshops.delete",
  "blogs.view",
  "blogs.create",
  "blogs.edit",
  "blogs.delete",
  "gallery.view",
  "gallery.create",
  "gallery.edit",
  "gallery.delete",
  "faqs.view",
  "faqs.create",
  "faqs.edit",
  "faqs.delete",
  "testimonials.view",
  "testimonials.create",
  "testimonials.edit",
  "testimonials.delete",
  "membershipPlans.view",
  "membershipPlans.create",
  "membershipPlans.edit",
  "membershipPlans.delete",
  "pages.view",
  "pages.create",
  "pages.edit",
  "pages.delete",
  "announcements.view",
  "announcements.manage",
  "notifications.view",
  "notifications.manage",
  "enquiries.view",
  "enquiries.edit",
  "enquiries.delete",
  "payments.view",
  "contactMessages.create",
  "contactMessages.view",
];

const rolePermissions = {
  super_admin: permissions,
  admin: permissions,
  teacher: [
    "dashboard.view",
    "programs.view",
    "workshops.view",
    "students.view",
    "blogs.view",
    "gallery.view",
    "profile.view",
    "profile.edit",
    "profile.own",
  ],
  student: [
    "dashboard.view",
    "programs.view",
    "workshops.view",
    "blogs.view",
    "gallery.view",
    "faqs.view",
    "testimonials.view",
    "membershipPlans.view",
    "pages.view",
    "announcements.view",
    "notifications.view",
    "enquiries.view",
    "contactMessages.create",
    "profile.view",
    "profile.edit",
    "profile.own",
  ],
};

const hasPermission = (role, permission) =>
  rolePermissions[role]?.includes(permission) || false;

module.exports = {
  permissions,
  rolePermissions,
  hasPermission,
};
